language: objective-c
osx_image: xcode9.2
rvm:
- 2.2         

env:
- TRAVIS_TAG="Deploy-2019.2.14f1" PROJECT_NAME="EnemyAI" UNITY_PROJECT_PATH="UnityExample" DEPLOY_UNITYPACKAGE="path set in deploy script"


cache:
  directories:
    - $UNITY_DOWNLOAD_CACHE

    
before_install:
- chmod a+x ./ci/*.sh

install:
- cat /etc/hosts
- ./ci/install-unity.sh

script:
- ./ci/build.sh
- ./ci/run-tests.sh

after_success:
- ./ci/export-unity-package.sh

before_deploy:
- DEPLOY_UNITYPACKAGE="$(ls -a release/*.zip | head -n 1)"

deploy:
  provider: releases
  github_token: $GITHUB_TOKEN
  api_key: $GITHUB_TOKEN
  file: $DEPLOY_UNITYPACKAGE
  cleanup: true
  overwrite: true
  on:
    tags: true 
    
notifications:
 - email: false